name: Build and Publish to JFrog

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Extract version from pom.xml
        id: extract-version
        run: echo "::set-output name=version::$(sed -n 's/.*<version>\(.*\)<\/version>.*/\1/p' pom.xml)"
      - name: Copy settings.xml
        run: |
          mkdir -p $HOME/.m2
          cp settings.xml $HOME/.m2/
      - name: Build and Test with Maven
        run: mvn clean install
      - name: Publish to JFrog
        run: |
          curl -u ${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_PASSWORD }} \
            -T target/blas-common-${{ steps.extract-version.outputs.version }}.jar \
            "https://dattest.jfrog.io/artifactory/blas-maven-libs-release/com/blas/blas-common/${{ steps.extract-version.outputs.version }}/blas-common-${{ steps.extract-version.outputs.version }}.xml"
